### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by stojanovicigi** [irrationalistic/atom-tasks#26]
[Enter steps to reproduce below:]

1. Add a project folder with at least one file with "todo" extension
2. Add a task
3. Press cmd + d keyboard shortcut to mark the task finished

**Atom Version**: 0.202.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package, v2.0.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755

TypeError: undefined is not a function
  at Object.module.exports.setMarker (/Users/igorstojanovic/.atom/packages/tasks/lib/tasksUtilities.coffee:219:28)
  at /Users/igorstojanovic/.atom/packages/tasks/lib/tasks.coffee:182:17
  at Array.map (native)
  at /Users/igorstojanovic/.atom/packages/tasks/lib/tasks.coffee:160:44
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at Object.module.exports.completeTask (/Users/igorstojanovic/.atom/packages/tasks/lib/tasks.coffee:159:12)
  at atom-text-editor.atom.commands.add.tasks:complete (/Users/igorstojanovic/.atom/packages/tasks/lib/tasks.coffee:57:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:11.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.3.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:05.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:copy (atom-text-editor.editor.is-focused)
  3x -0:04.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:paste (atom-text-editor.editor.is-focused)
  5x -0:02.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.0 tasks:complete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.2
command-logger, v0.23.0
editor-stats, v0.17.0
linter, v0.12.6
linter-write-good, v0.4.3
monokai, v0.14.0
save-session, v0.15.3
tasks, v2.0.1
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by irrationalistic** [comment]
Strange! Can you send the todo content that you have that caused the issue? Internally the tests pass fine, so it might be something weird with the content or command order.

You might also try re-installing the plugin to see if it persists!

**Comment by stojanovicigi** [comment]
The content doesn't matter. I tried to reinstall the plugin, but the bug still persist.
Here's a small video which shows all steps I did.
https://dl.dropboxusercontent.com/u/3437823/tasksProblem.mov

**Comment by irrationalistic** [comment]
Thanks for the video! I'll take a look and see if I can reproduce the problem.

**Comment by irrationalistic** [comment]
So it looks like a method that gets a screen column for a given token was removed in a recent commit to the atom core: https://github.com/atom/atom/commit/2379b3803fbc9e09dce4192dc4c01b93d1c23249#diff-dc35bc3db558965c0b4211dd52bc19cbL294

Now looking for an alternative!

**Comment by stojanovicigi** [comment]
@irrationalistic Works now. Thanks.
