### ISSUE TITLE
Failed to load the tasks package

### ISSUE THREAD

**Issue by gnarmedia** [irrationalistic/atom-tasks#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 15.04
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package, v2.4.0

### Stack Trace

Failed to load the tasks package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'status-bar-tasks'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'status-bar-tasks'. A type with that name is already registered.
  at Error (native)
  at Object.<anonymous> (/home/adam/.atom/packages/tasks/lib/views/task-status-view.coffee:65:27)
  at Object.<anonymous> (/home/adam/.atom/packages/tasks/lib/views/task-status-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/adam/.atom/packages/tasks/lib/tasks.coffee:8:18)
  at Object.<anonymous> (/home/adam/.atom/packages/tasks/lib/tasks.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:759:34)
  at /usr/share/atom/resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:485:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -8:20.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
  6x -8:20.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-make",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-less",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-xml",
      "block-comment",
      "fold-comments",
      "vim-mode",
      "git-wip"
    ],
    "themes": [
      "atom-material-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-jade, v0.3.0
atom-material-ui, v0.5.20
atom-pair, v2.0.5
atom-ternjs, v0.7.1
atomdo, v0.4.0
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.3
git-diff-details, v0.20.0
highlight-selected, v0.10.1
imdone-atom, v1.1.19
linter, v1.3.4
linter-csslint, v1.0.5
linter-eslint, v3.0.2
method-separator, v0.1.3
motepair, v0.20.0
pigments, v0.11.0
pretty-json, v0.4.1
project-manager, v1.15.11
project-view, v0.1.2
react, v0.12.6
stash-tabs, v0.1.0
tasks, v2.4.0
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Comment by irrationalistic** [comment]
Hmm, that is a strange issue. I'll double check to see if any of the other packages you have installed would cause conflict. Have you tried restarting atom? Or re-installing the tasks package?

**Comment by irrationalistic** [comment]
Any chance this has started working again?

**Comment by irrationalistic** [comment]
I'm going to close this and assume that things are working correctly! Feel free to re-open it if they aren't though.

**Comment by NeLk42** [comment]
Hi @irrationalistic,

I'm looking forward being able to use what looks to be an amazing package.

I'm under a pretty nasty proxy that blocks public repos, so I had to install your package by linking it with atom, which is probably what is creating this issue.

[Enter steps to reproduce below:]

1. Fresh atom
2. Download latest tasks.zip
3. Unzip in folder
4. @Command_Line `apm link C;\<path-to-folder>\atom-tasks-2.6.6
5. Open Atom
6. Boom


**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package, v2.6.6


### Stack Trace

Failed to load the tasks package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/SWDTOOLS/atom-tasks-2.6.6/lib/tasks.coffee:2:5)
    at Object.<anonymous> (file:///C:/SWDTOOLS/atom-tasks-2.6.6/lib/tasks.coffee:1:1)
    at Module._compile (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:766:27)
    at C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:121:28
    at Package.module.exports.Package.measure (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:94:15)
    at Package.module.exports.Package.load (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:108:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:468:14)
    at C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:412:19
    at Config.module.exports.Config.transact (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:407:19)
    at C:\Users\44037707\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:811:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
tasks, v2.6.6 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by irrationalistic** [comment]
@NeLk42: Maybe you need to run `npm install` from the package repo folder? Underscore is a dependency of the project itself...

**Comment by NeLk42** [comment]
👍
