### ISSUE TITLE
Failed to activate the tasks package

### ISSUE THREAD

**Issue by blomma** [irrationalistic/atom-tasks#44]
[Enter steps to reproduce below:]

1. Updated tasks package from inside Atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package, v2.5.1

### Stack Trace

Failed to activate the tasks package

```
At Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
  at Object.module.exports.updateGrammar (/Users/blomma/.atom/packages/tasks/lib/tasks.coffee:89:7)
  at /Users/blomma/.atom/packages/tasks/lib/tasks.coffee:50:22
  at Config.module.exports.Config.observeKeyPath (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
  at Config.module.exports.Config.observe (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
  at Object.module.exports.activate (/Users/blomma/.atom/packages/tasks/lib/tasks.coffee:49:17)
  at Package.module.exports.Package.activateNow (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
  at exit (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -0:21.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-duotone-dark-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "/Users/blomma/Dropbox/Projects/private",
    "audioBeep": false,
    "themes": [
      "atom-material-ui",
      "duotone-dark-syntax"
    ],
    "openEmptyEditorOnStart": false
  },
  "tasks": {
    "baseMarker": "-"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.7.1
duotone-dark-syntax, v0.3.0
file-icons, v1.6.11
indentation-indicator, v0.6.0
language-aspx, v0.4.0
language-cshtml, v0.1.1
language-fish-shell, v1.0.2
language-lua, v0.9.4
language-powershell, v2.1.0
language-swift, v0.4.0
language-tmux, v0.4.0
one-tab, v0.8.0
remote-atom, v1.2.7
soft-wrap-indicator, v0.7.0
tasks, v2.5.1

# Dev
No dev packages
```

**Comment by jbjonesjr** [comment]
👍

**Comment by irrationalistic** [comment]
Did restarting fix this? This seems to correspond with outdated code, which might have to do with caching or something like that.

**Comment by blomma** [comment]
Restarting did indeed fix the problem and it hasn't shown up since, so
yeah, caching seems the likely culprit. You can close this issue.

**Comment by irrationalistic** [comment]
Thanks for checking on that! I'm not actually sure how atom handles the update process. Seems like it keeps some parts in memory while others get re-loaded. Might have just been a race-condition with which part got re-loaded first.

**Comment by filjoseph1989** [comment]
I'm encountering this issue as of now
