### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokens' of undefined

### ISSUE THREAD

**Issue by willfanguy** [irrationalistic/atom-tasks#51]
[Enter steps to reproduce below:]

1. Right-click tab
2. Split left
    Also occurred on Split Right

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.4
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package, v2.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At /Users/Will/.atom/packages/tasks/lib/views/task-status-view.coffee:78

TypeError: Cannot read property 'tokens' of undefined
    at /Users/Will/.atom/packages/tasks/lib/views/task-status-view.coffee:78:42
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:399:19
    at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
    at Function.countBy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:398:9)
    at status-bar-tasks.TaskStatusView.updateStatus (/Users/Will/.atom/packages/tasks/lib/views/task-status-view.coffee:76:18)
    at status-bar-tasks.TaskStatusView.subscribeToActiveTextEditor (/Users/Will/.atom/packages/tasks/lib/views/task-status-view.coffee:55:19)
    at /Users/Will/.atom/packages/tasks/lib/views/task-status-view.coffee:22:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:623:15)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:712:15)
    at Pane.module.exports.Pane.splitLeft (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:668:19)
    at atom-tabs.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:392:31)
    at Object.addElementCommands.tabs:split-left (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:122:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:78:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:51.3.0 markdown-writer:indent-list-line (atom-text-editor.editor.is-focused)
     -2:47.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:47.4.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -2:47.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:42 core:backspace (atom-text-editor.editor.is-focused)
     -2:41.3.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -2:41.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:36.1.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
  7x -2:31.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:19.3.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
 17x -2:17.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:47.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 12x -1:44.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31 core:save (atom-text-editor.editor.is-focused)
     -0:15.7.0 tabs:split-right (div.title)
     -0:01.3.0 tabs:split-left (div.title)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-format"
    ],
    "themes": [
      "atom-dark-ui",
      "adventurous-syntax"
    ]
  },
  "tasks": {
    "baseMarker": "-",
    "completeMarker": " ",
    "dateFormat": "YY-MM-DD HH:mm"
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.2.0
markdown-writer, v2.2.0
marked, v0.1.10
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
tasks, v2.6.0
wordcount, v2.5.0

# Dev
No dev packages
```

**Comment by irrationalistic** [comment]
I can't seem to reproduce this. If you restart the editor can you get it to happen again? Maybe try re-installing the plugin?

**Comment by willfanguy** [comment]
Restart fixed it. Closing...

**Comment by blomma** [comment]
Not sure if this is the correct way to do it, but I'm getting this error also. In my case restarting doesnt help, but also for me when i restart Atom it starts up with a Task file as the first window, so that might be the difference. If i restart Atom without it opening a task file directly the error doesnt show. So i think there is something going on with opening an Atom window and having a task file open directly with opening Atom that triggers this error.


[Enter steps to reproduce below:]

1. Open a fresh instance of Atom where the last file open was a Task file which means Atoms opens with that file directly.

**Atom Version**: 1.9.0-beta0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package, v2.6.0


### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At /C:/Users/Mikael/.atom/packages/tasks/lib/views/task-status-view.coffee:78

TypeError: Cannot read property 'tokens' of undefined
    at file:///C:/Users/Mikael/.atom/packages/tasks/lib/views/task-status-view.coffee:42:40
    at C:\Users\Mikael\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\jasmine-tagged\node_modules\jasmine-focused\node_modules\jasmine-node\node_modules\underscore\underscore.js:399:19
    at Function._.each._.forEach (C:\Users\Mikael\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\jasmine-tagged\node_modules\jasmine-focused\node_modules\jasmine-node\node_modules\underscore\underscore.js:153:9)
    at Function.countBy (C:\Users\Mikael\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\jasmine-tagged\node_modules\jasmine-focused\node_modules\jasmine-node\node_modules\underscore\underscore.js:398:9)
    at status-bar-tasks.TaskStatusView.updateStatus (file:///C:/Users/Mikael/.atom/packages/tasks/lib/views/task-status-view.coffee:41:16)
    at status-bar-tasks.TaskStatusView.subscribeToActiveTextEditor (file:///C:/Users/Mikael/.atom/packages/tasks/lib/views/task-status-view.coffee:26:6)
    at status-bar-tasks.TaskStatusView.initialize (file:///C:/Users/Mikael/.atom/packages/tasks/lib/views/task-status-view.coffee:12:6)
    at Object.module.exports.consumeStatusBar (file:///C:/Users/Mikael/.atom/packages/tasks/lib/tasks.coffee:123:17)
    at Provider.module.exports.Provider.provide (C:\Users\Mikael\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\Mikael\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check",
      "qolor"
    ],
    "followSymlinks": true,
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/blomma/Dropbox/Projects/private",
    "themes": [
      "atom-material-ui",
      "duotone-dark-syntax"
    ]
  },
  "tasks": {
    "baseMarker": "-"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.2.13 (active)
dash, v1.6.1 (inactive)
duotone-dark-syntax, v1.0.0 (active)
file-icons, v1.7.15 (inactive)
git-diff-details, v1.3.0 (inactive)
indentation-indicator, v0.6.0 (inactive)
keyboard-localization, v1.4.18 (inactive)
language-aspx, v0.4.0 (inactive)
language-cshtml, v0.2.1 (inactive)
language-fish-shell, v1.0.4 (inactive)
language-lua, v0.9.4 (inactive)
language-powershell, v2.1.1 (inactive)
language-swift, v0.4.0 (inactive)
language-tmux, v0.4.0 (inactive)
language-vb, v0.1.0-pre1 (inactive)
language-viml, v1.0.0 (inactive)
markdown-writer, v2.3.5 (inactive)
marked, v0.1.10 (inactive)
one-tab, v0.9.0 (inactive)
qolor, v0.2.2 (inactive)
remote-atom, v1.3.9 (inactive)
rester, v1.0.2 (inactive)
soft-wrap-indicator, v0.7.0 (inactive)
sort-lines, v0.14.0 (inactive)
tasks, v2.6.0 (inactive)
wordcount, v2.6.0 (inactive)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.2.0 (inactive)
git-diff, v1.0.1 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.3.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by irrationalistic** [comment]
Does it repro in the non-beta version?

**Comment by blomma** [comment]
No, in non-beta (1.8) the error never shows. In beta 1.9 it always manifests itself.

**Comment by irrationalistic** [comment]
Interesting. I wonder what would have changed? I can try to dig, but would love some help if you have the cycles :)

**Comment by blomma** [comment]
Hey Chris, i always appreciate a good challenge, but I'm going on a long
vacation in a couple of days so the most I can offer is if you need an
extra tester :)

**Comment by nirfse** [comment]
> ```
> /home/user/.atom/packages/tasks/lib/views/task-status-view.coffee:42
> Stack Trace:
> TypeError: Cannot read property 'tokens' of undefined
>     at /home/user/.atom/packages/tasks/lib/views/task-status-view.coffee:42:40
>     at /usr/share/atom-beta/resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:399:19
>     at Function._.each._.forEach (/usr/share/atom-beta/resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
>     at Function.countBy (/usr/share/atom-beta/resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:398:9)
>     at status-bar-tasks.TaskStatusView.updateStatus (/home/user/.atom/packages/tasks/lib/views/task-status-view.coffee:41:16)
>     at status-bar-tasks.TaskStatusView.subscribeToActiveTextEditor (/home/user/.atom/packages/tasks/lib/views/task-status-view.coffee:26:6)
>     at status-bar-tasks.TaskStatusView.initialize (/home/user/.atom/packages/tasks/lib/views/task-status-view.coffee:12:6)
>     at Object.module.exports.consumeStatusBar (/home/user/.atom/packages/tasks/lib/tasks.coffee:123:17)
>     at Provider.module.exports.Provider.provide (/usr/share/atom-beta/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
>     at /usr/share/atom-beta/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)`

Just installed plugin for the first time on `Atom 1.9.0-beta0`.

**Comment by irrationalistic** [comment]
Yeah, i'm seeing this on beta as well. Haven't had time to look into it yet, but i'll try to debug and see what's going on!
