### ISSUE TITLE
Uncaught TypeError: Cannot read property 'every' of undefined

### ISSUE THREAD

**Issue by kziemski** [irrationalistic/atom-tasks#78]
tried to archive a task

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.6.6

### Stack Trace

Uncaught TypeError: Cannot read property 'every' of undefined

```
At C:\Users\PCOMP\AppData\Local\atom\app-1.19.0-beta0\resources\app\node_modules\text-buffer\lib\text-buffer.js:912

TypeError: Cannot read property 'every' of undefined
    at /packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/text-buffer.js:907:24)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor.js:1672:32)
    at Object.tasksArchive (/packages/tasks/lib/tasks.coffee:342:12)
    at /packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:46.3.0 core:save (input.hidden-input)
     -0:44.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:43.3.0 editor:consolidate-selections (input.hidden-input)
     -0:43.3.0 core:cancel (input.hidden-input)
     -0:42.1.0 core:select-all (input.hidden-input)
     -0:41.5.0 core:move-up (input.hidden-input)
     -0:41 core:move-right (input.hidden-input)
  3x -0:40.7.0 core:move-down (input.hidden-input)
  3x -0:39.8.0 core:backspace (input.hidden-input)
  2x -0:38.1.0 core:move-right (input.hidden-input)
  2x -0:37.5.0 core:move-down (input.hidden-input)
     -0:36.8.0 core:move-up (input.hidden-input)
     -0:36.5.0 core:move-right (input.hidden-input)
     -0:36.1.0 editor:move-to-end-of-word (input.hidden-input)
     -0:26.6.0 tasks:complete (span.syntax--tasks.syntax--text.syntax--md)
  2x -0:23.5.0 tasks:archive (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 1.16.0 
ionide-fsharp 1.9.3 
tasks 2.6.6 
```

**Comment by irrationalistic** [comment]
Can you add a little more information to this? I'm not entirely sure why this would be undefined; are you able to reproduce it yourself? Is there a set of steps you have to do or is it any time you try to archive tasks?

**Comment by rjglasse** [comment]
Just updated to Atom 1.19.0 x64 (on macOS 10.12.6) and had a similar trace (see below).

[Enter steps to reproduce:]

1. Created a fresh .todo file
2. Added three tasks
3. Marked one task as done
4. Invoked archive (error thrown; no changes made to tasks)

n.b. both keyboard shortcut and command palette tested to invoke archive (same result) 

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.6.6

### Stack Trace

Uncaught TypeError: Cannot read property 'every' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904

TypeError: Cannot read property 'every' of undefined
    at /packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1672:32)
    at Object.tasksArchive (/packages/tasks/lib/tasks.coffee:342:12)
    at /packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:591:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:449:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -4:12.1.0 editor:select-to-first-character-of-line (input.hidden-input)
     -4:11.3.0 core:copy (input.hidden-input)
     -3:19.6.0 settings-view:open (input.hidden-input)
     -0:39.2.0 command-palette:toggle (input.hidden-input)
     -0:36 editor:consolidate-selections (input.hidden-input)
     -0:36 core:cancel (input.hidden-input)
     -0:30.4.0 command-palette:toggle (input.hidden-input)
     -0:26.4.0 editor:consolidate-selections (input.hidden-input)
     -0:26.4.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
autocomplete-emojis 2.5.0 
autocomplete-java 1.2.7 
autocomplete-python 1.10.0 
busy-signal 1.4.3 
calc 0.4.0 
file-icons 2.1.10 
git-clone 0.2.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
go-debug 1.5.0 
go-get 2.1.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
graphviz-preview 1.7.0 
Hydrogen 1.19.0 
hyperclick 0.1.3 
hyperlink-hyperclick 1.3.4 
intentions 1.1.5 
language-dot 1.7.0 
language-latex 1.1.0 
latex 0.45.0 
latex-autocomplete 1.0.0 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
lines 0.13.1 
linter 2.2.0 
linter-chktex 1.3.1 
linter-clojure 1.1.3 
linter-flake8 2.2.1 
linter-javac 1.9.4 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.3 
markdown-folder 0.5.0 
monokai 0.24.0 
open-recent 5.0.0 
pdf-view 0.59.0 
process-palette 0.14.0 
proto-repl 1.4.21 
script 3.15.0 
sort-lines 0.14.0 
tasks 2.6.6 
unregistered 0.1.0 
Zen 0.18.0 
```

**Comment by millipz** [comment]
Same Issue here on Windows 7 / Atom 1.19.0 x64 / Tasks 2.6.6

...\AppData\Local\atom\app-1.19.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:904

Hide Stack Trace
TypeError: Cannot read property 'every' of undefined
    at file:///C:/Users/mphillips/.atom/packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor.js:1672:32)
    at Object.tasksArchive (file:///C:/Users/mphillips/.atom/packages/tasks/lib/tasks.coffee:342:12)
    at HTMLElement.atom.commands.add.tasks:archive (file:///C:/Users/mphillips/.atom/packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:265:35)
    at C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\mphillips\AppData\Local\atom\app-1.19.0\resources\app\src\window-event-handler.js:3:65)

**Comment by Guerillero** [comment]
It threw this error for me. 

`TypeError: Cannot read property 'every' of undefined
    at file:///C:/Users/<UN>/.atom/packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\<UN>\AppData\Local\atom\app-1.19.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\<UN>\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor.js:1672:32)
    at Object.tasksArchive (file:///C:/Users/<UN>/.atom/packages/tasks/lib/tasks.coffee:342:12)
    at HTMLElement.atom.commands.add.tasks:archive (file:///C:/Users/<UN>/.atom/packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\<UN>\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (C:\Users\39174\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\<UN>\AppData\Local\atom\app-1.19.0\resources\app\src\command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\<UN>\AppData\Local\atom\app-1.19.0\resources\app\src\atom-environment.js:1344:34)
    at EventEmitter.outerCallback (C:\Users\<UN>\AppData\Local\atom\app-1.19.0\resources\app\src\application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

**Comment by rfoust** [comment]
Just got this error.

[Enter steps to reproduce:]

1. Select shift-command-a to archive, error is immediately thrown.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.6.6


### Stack Trace

Uncaught TypeError: Cannot read property 'every' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904

TypeError: Cannot read property 'every' of undefined
    at /packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1672:32)
    at Object.tasksArchive (/packages/tasks/lib/tasks.coffee:342:12)
    at /packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -5:22 tasks:archive (input.hidden-input)
  6x -0:40.5.0 core:backspace (input.hidden-input)
  5x -0:29.2.0 core:move-up (input.hidden-input)
     -0:28.1.0 core:move-down (input.hidden-input)
  3x -0:27.8.0 core:backspace (input.hidden-input)
     -0:17.6.0 core:save (input.hidden-input)
  2x -0:14.3.0 tasks:archive (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
file-icons 2.1.10 
git-plus 7.9.3 
git-time-machine 1.5.9 
language-powershell 4.0.0 
minimap 4.29.6 
seti-syntax 1.1.3 
seti-ui 1.9.0 
split-diff 1.4.3 
tasks 2.6.6 
```

**Comment by derrickwheals** [comment]
Also getting this issue on Windows 10, Atom 1.19.1 when archiving tasks after upgrading Atom

1. CTRL-SHIFT-A in a taskpaper file to archive done tasks

**Atom**: 1.19.1 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.6.6


### Stack Trace

Uncaught TypeError: Cannot read property 'every' of undefined

```
At C:\Users\derrick.wheals\AppData\Local\atom\app-1.19.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:904

TypeError: Cannot read property 'every' of undefined
    at /packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor.js:1672:32)
    at Object.tasksArchive (/packages/tasks/lib/tasks.coffee:342:12)
    at /packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.1/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.1/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:46.4.0 intentions:highlight (input.hidden-input)
     -9:45.9.0 core:save (input.hidden-input)
     -9:41 intentions:highlight (input.hidden-input)
     -9:40.8.0 core:save (input.hidden-input)
 41x -9:27.6.0 core:move-down (input.hidden-input)
     -0:41.6.0 intentions:highlight (input.hidden-input)
     -0:41.2.0 tasks:complete (input.hidden-input)
  8x -0:40.1.0 core:move-down (input.hidden-input)
 21x -0:36.1.0 intentions:highlight (input.hidden-input)
     -0:34.9.0 core:save (input.hidden-input)
  2x -0:22 intentions:highlight (input.hidden-input)
     -0:21.5.0 tasks:archive (input.hidden-input)
```

### Non-Core Packages

```
all-shades-of-blue-syntax 0.5.5 
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-mdtoc 0.8.3 
atom-monokai 0.10.9 
atom-python-run 0.8.1 
atom-touch-events 0.23.0 
autocomplete-en-en 0.2.0 
autocomplete-python 1.10.0 
busy-signal 1.4.3 
click-link 1.0.11 
custom-folds 1.9.4 
dark-flat-ui 1.2.4 
date 1.2.2 
duotone-blue-dark-syntax 1.4.0 
file-icons 2.1.10 
flatwhite-syntax 0.8.1 
fold-lines 0.2.2 
fonts 3.0.2 
googlesearch 1.5.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.3 
hyperlink-hyperclick 1.3.4 
intellij-darcula-syntax 1.0.11 
intentions 1.1.5 
language-gfm-enhanced 0.92.0 
language-gherkin 1.0.4 
language-markdown 0.25.1 
linter 2.2.0 
linter-markdown 5.1.0 
linter-ui-default 1.6.4 
markdown-pdf 1.5.4 
markdown-preview-enhanced 0.14.7 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.6.1 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
monokai 0.24.0 
monokai-seti 0.9.0 
newbound-dark-syntax 1.1.0 
nucleus-dark-ui 0.12.3 
one-dark-atom 1.3.0 
one-o-eight-syntax 0.28.3 
pdf-view 0.59.0 
pen-paper-coffee-syntax 0.14.9 
pigments 0.40.2 
project-manager 3.3.5 
pubster-syntax 3.0.1 
scratch 1.2.0 
seti-ui 1.9.0 
slack-ui 0.8.0 
sort-lines 0.14.0 
split-diff 1.4.3 
tasks 2.6.6 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tool-bar-markdown-writer 0.3.0 
treeview-file-highlight 0.8.0 
wombat-dark-syntax 1.2.0 
wombat-light-syntax 1.2.0 
Zen 0.18.0 
```

**Comment by t-hughes** [comment]
Also got this error when trying to do a shift + cmd + A on macOS Sierra 10.12.6
Atom version 1.19.1

**Comment by mike-zarandona** [comment]
Just got this error when trying to do a `shift` + `cmd` + `A` on MacOS Sierra 10.12.6:

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.6.6


### Stack Trace

Uncaught TypeError: Cannot read property 'every' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904

TypeError: Cannot read property 'every' of undefined
    at /packages/tasks/lib/tasks.coffee:350:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1672:32)
    at Object.tasksArchive (/packages/tasks/lib/tasks.coffee:342:12)
    at /packages/tasks/lib/tasks.coffee:68:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -6:41.4.0 editor:newline (input.hidden-input)
  2x -6:39.5.0 core:backspace (input.hidden-input)
     -6:38.3.0 core:save (input.hidden-input)
     -3:48 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:47.4.0 editor:consolidate-selections (input.hidden-input)
     -3:47.4.0 core:cancel (input.hidden-input)
     -3:39.7.0 tasks:complete (input.hidden-input)
     -3:37.5.0 core:backspace (input.hidden-input)
     -3:36.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:31.7.0 core:move-down (input.hidden-input)
     -3:31.6.0 tasks:complete (input.hidden-input)
  2x -3:31.1.0 core:move-down (input.hidden-input)
     -3:22.6.0 tasks:complete (input.hidden-input)
     -3:22.1.0 core:move-down (input.hidden-input)
     -0:44.5.0 core:save (input.hidden-input)
     -0:41.5.0 tasks:archive (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-prettify 0.1.3 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
craft-twig 0.4.0 
docblockr 0.11.0 
editorconfig 2.2.2 
file-icons 2.1.10 
fold-comments 0.6.0 
intentions 1.1.5 
jsformat 0.9.3 
jshint 1.8.6 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-ui-default 1.6.4 
merge-conflicts 1.4.5 
minimap 4.29.6 
php-twig 4.0.0 
pigments 0.40.2 
pretty-json 1.6.4 
project-manager 3.3.5 
rest-client 1.3.1 
tabs-to-spaces 1.0.3 
tasks 2.6.6 
title-case 0.4.0 
todo 0.6.0 
```

```

**Comment by rfoust** [comment]
Same thing in Atom 1.19.2.

**Comment by derrickwheals** [comment]
Any chance of this getting fixed soon?

**Comment by stefanthaler** [comment]
In my understanding, the problem is that the property '**editor.buffer.lines'** in 'lib/tasks.coffee' cannot be accessed anymore. 

What worked for me was replacing  '**_editor.buffer.lines_**' with '**editor.buffer.getLines()**' in line 350 and line 383 of the lib/tasks.coffee file.

**Comment by derrickwheals** [comment]
Thanks @stefanthaler  - worked for me too...

**Comment by Off76** [comment]
@stefanthaler Perfect thanks 👍

**Comment by Guerillero** [comment]
@stefanthaler I turned your fix into a PR (#81) so it can be sent out to everyone.

**Comment by en0b** [comment]
@stefanthaler worked for me too! awesome! don't forget to restart atom after the change..

**Comment by stefanthaler** [comment]
@Guerillero  cool, thanks :+1:
