### ISSUE TITLE
"Cannot find module" error on Atom 1.25.0-beta.0.

### ISSUE THREAD

**Issue by phyllisstein** [irrationalistic/atom-tasks#93]
Hey there! Having some trouble using Tasks with the new beta of Atom---looks like they may have removed a package on you, but I haven't dug into the code myself to check. Thanks in advance for any insight you can offer!

---

### Steps to Reproduce

1. Install Tasks with a beta version of Atom.
2. :boom:

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.10.0

### Stack Trace

Failed to load the tasks package

```
At Cannot find module 'undefined/node_modules/season/lib/cson.js'

Error: Cannot find module 'undefined/node_modules/season/lib/cson.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/tasks/lib/tasks.coffee:3:8)
    at /packages/tasks/lib/tasks.coffee:1:1)
    at /packages/tasks/lib/tasks.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.transact (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:815:20)
    at PackageManager.loadPackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:829:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-center-comment 0.1.1 
atom-ide-ui 0.8.1 
atom-markboard 2.0.0 
atom-material-ui 2.1.2 
atom-npm-outdated 0.13.1 
atom-quokka 1.0.52 
atom-typescript 12.1.2 
atom-wallaby 1.0.22 
auto-close-html2 0.7.0 
autoupdate-packages 1.3.1 
boxy-monokai-syntax 0.0.0 
boxy-nova-syntax 0.0.0 
boxy-ocean-syntax 0.0.0 
boxy-yesterday-syntax 0.0.0 
bracket-padder 0.4.2 
build 0.70.0 
center-editor 0.4.1 
chmod 0.1.1 
collapse-then-reveal 2.0.4 
copy-path 0.5.1 
docblockr 0.13.6 
dockerletion 0.2.0 
duplicate-and-comment 0.2.5 
file-icons 2.1.16 
file-types 0.5.5 
fill-line 1.0.0 
git-clone 0.2.0 
git-diff-details 1.4.0 
git-edit-atom 0.3.3 
git-plus 7.10.0 
git-rebase 0.1.1 
gitignores 0.3.2 
hey-pane 1.1.0 
highlight-selected 0.13.1 
intentions 1.1.5 
key-peek 0.2.12 
keybinding-cheatsheet 0.1.1 
language-babel 2.84.0 
language-docker 1.1.8 
language-elixir 0.22.0 
language-fontforge 1.2.0 
language-gitignore 0.3.0 
language-jenkinsfile 0.1.1 
language-latex 1.1.1 
language-nginx 0.6.2 
language-pug 0.0.22 
language-restructuredtext 1.1.0 
language-scala 1.1.9 
language-terraform 0.8.1 
language-todo-extra-words 0.2.0 
latex 0.49.0 
latex-autocomplete 1.1.1 
less-than-slash 0.18.0 
linter-chktex 1.3.1 
linter-docker 0.3.0 
linter-eslint 8.4.1 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-rubocop 2.2.3 
linter-shellcheck 1.4.6 
linter-tslint 1.9.0 
lorem-gibson 2.3.0 
markdown-writer 2.7.3 
pain-split 1.4.0 
pdf-view 0.65.0 
project-manager 3.3.5 
project-viewer 1.3.0 
pure-syntax 0.3.0 
quick-file-actions 0.2.2 
related 0.3.5 
resize-indent 0.3.0 
sort-lines 0.18.0 
split-diff 1.5.2 
stop-cursor-blinking 1.0.0 
tasks 2.10.0 
teletype 0.8.0 
todo-show 2.1.0 
toggle-markdown-task 0.6.0 
toggle-quotes 1.1.0 
touchbar 0.6.1 
wordcount 2.10.4 
zentabs 0.8.9 
```

**Comment by irrationalistic** [comment]
I _think_ i might know what's going on here. I'll try to get a fix up quickly!

**Comment by irrationalistic** [comment]
Just published to APM, give it a try and confirm it works?

**Comment by phyllisstein** [comment]
Like a charm! Thanks so much for looking into it!
