### ISSUE TITLE
Failed to activate the tasks package

### ISSUE THREAD

**Issue by filjoseph1989** [irrationalistic/atom-tasks#94]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.9.1

### Stack Trace

Failed to activate the tasks package

```
At this.registry.startIdForScope is not a function

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:428:30)
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:53:36)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:207:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:126:41)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at buffer.onDidChangeLanguageMode (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:741:13)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.setLanguageMode (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1373:28)
    at grammarScoresByBuffer.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/src/grammar-registry.js:310:24)
    at Map.forEach (native)
    at GrammarRegistry.grammarAddedOrUpdated (~/AppData/Local/atom/app-1.24.0/resources/app/src/grammar-registry.js:287:38)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/first-mate/lib/grammar-registry.js:80:26)
    at GrammarRegistry.addGrammar (~/AppData/Local/atom/app-1.24.0/resources/app/src/grammar-registry.js:355:40)
    at Object.updateGrammar (/packages/tasks/lib/tasks.coffee:125:19)
    at /packages/tasks/lib/tasks.coffee:54:22
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.24.0/resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.24.0/resources/app/src/config.js:155:27)
    at Object.activate (/packages/tasks/lib/tasks.coffee:53:17)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:670:36)
```

### Commands

```
```

### Non-Core Packages

```
aligner-javascript 1.3.0 
alignment 1.1.5 
atom-beautify 0.30.9 
atom-bootstrap3 1.2.12 
atom-css-clean 2.24.1 
atom-ide-ui 0.8.1 
atom-prettify 0.1.3 
atom-terminal 0.8.0 
atomatigit 1.5.5 
autocomplete-html-entities 0.2.0 
blade-snippets 0.2.0 
bliss-syntax 0.3.3 
bliss-ui 0.6.0 
block-comment-plus 0.5.1 
color-picker 2.2.5 
docblockr 0.13.6 
emmet 2.4.3 
file-icons 2.1.16 
flex-tool-bar 0.15.1 
git-control 0.9.0 
git-log 0.4.1 
goto-definition 1.3.4 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-html 0.4.1 
ide-php undefined 
language-diff 0.7.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
laravel-5-snippets 0.19.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
no-title-bar 1.11.4 
one-dark-vivid-syntax 1.8.0 
php-cs-fixer 4.1.1 
php-hyperclick 1.2.1 
pretty-json 1.6.4 
pure-syntax 0.3.0 
redeye-ui 0.5.0 
release-notes 0.53.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.3 
tab-length 0.1.0 
tabs-to-spaces 1.0.3 
tasks 2.9.1 
teletype 0.7.0 
todo 0.6.0 
tool-bar 1.1.6 
tool-bar-main 0.0.11 
v-bootstrap4 0.2.2 
```

**Comment by irrationalistic** [comment]
@filjoseph1989 : can you check if updating the package fixes this issue? I pushed a fix out last night!

**Comment by johnhathaway** [comment]
@irrationalistic  I'm not OP but the update did fix the issue for me. Thanks!

**Comment by irrationalistic** [comment]
I'll close for now, but feel free to re-open if it persists!

**Comment by jcranendonk** [comment]
I just got the same error message for 2.10.1 on Atom 1.24.0. Need any logs or traces?

**Comment by irrationalistic** [comment]
@jcranendonk: are you still getting the error? Would love to have the stack so we can see all the version info!

**Comment by jcranendonk** [comment]
```
Grammar missing required scopeName property: /Users/jeroencranendonk/.atom/TasksGrammar.cson
Hide Stack Trace
Error: Grammar missing required scopeName property: /Users/jeroencranendonk/.atom/TasksGrammar.cson
    at GrammarRegistry.module.exports.GrammarRegistry.readGrammarSync (<embedded>:79521:21)
    at GrammarRegistry.module.exports.GrammarRegistry.loadGrammarSync (<embedded>:79547:28)
    at GrammarRegistry.loadGrammarSync (<embedded>:24021:40)
    at Object.updateGrammar (/Users/jeroencranendonk/.atom/packages/tasks/lib/tasks.coffee:198:34)
    at /Users/jeroencranendonk/.atom/packages/tasks/lib/tasks.coffee:73:24
    at Config.module.exports.Config.observeKeyPath (<embedded>:22207:13)
    at Config.module.exports.Config.observe (<embedded>:21688:27)
    at Object.activate (/Users/jeroencranendonk/.atom/packages/tasks/lib/tasks.coffee:70:19)
    at Package.activateNow (<embedded>:72392:33)
    at measure (<embedded>:72368:33)
    at Package.measure (<embedded>:72250:25)
    at activationPromise.Promise (<embedded>:72362:20)
    at Package.activate (<embedded>:72360:38)
    at PackageManager.activatePackage (<embedded>:25512:42)
    at config.transactAsync (<embedded>:25487:36)
    at Config.module.exports.Config.transactAsync (<embedded>:21900:24)
    at PackageManager.activatePackages (<embedded>:25485:23)
    at PackageManager.activate (<embedded>:25464:50)
    at loadStatePromise.loadState.then (<embedded>:1081:27)
```

**Comment by irrationalistic** [comment]
Hmm, can you confirm the version of tasks you are on? The line number doesn't seem to match the current version!

**Comment by jcranendonk** [comment]
Atom says 2.10.1:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/3082871/37527490-c6e575e2-28f7-11e8-9fa0-6cf2d693f2fc.png">

**Comment by irrationalistic** [comment]
I hate to ask this, but could you try re-installing it?

**Comment by jcranendonk** [comment]
I reinstalled it—I'll update the issue if the error recurs.

**Comment by ekoepplin** [comment]
same error  here as well:
OS 10.12.5
ATOM 1.25
Occured after using `sync-restore`, reinstalling doesnt work as well

**Comment by irrationalistic** [comment]
@hugeme: do you have a stack trace?

**Comment by ppo** [comment]
Atom 1.30.0, Tasks 2.10.1
Tried to re-install it but still not working.

```
Error: Grammar missing required scopeName property: /Users/ppo/.atom/TasksGrammar.cson
    at GrammarRegistry.createGrammar (<embedded>:24828:21)
    at GrammarRegistry.readGrammarSync (<embedded>:24820:23)
    at GrammarRegistry.loadGrammarSync (<embedded>:24789:32)
    at Object.updateGrammar (/Users/ppo/macbook/tilde/.atom/packages/tasks/lib/tasks.coffee:198:34)
    at /Users/ppo/macbook/tilde/.atom/packages/tasks/lib/tasks.coffee:85:24
    at Config.observeKeyPath (<embedded>:22944:11)
    at Config.observe (<embedded>:22373:25)
    at Object.activate (/Users/ppo/macbook/tilde/.atom/packages/tasks/lib/tasks.coffee:82:19)
    at Package.activateNow (<embedded>:75328:33)
    at measure (<embedded>:75304:33)
    at Package.measure (<embedded>:75186:25)
    at activationPromise.Promise (<embedded>:75298:20)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:75296:38)
    at PackageManager.activatePackage (<embedded>:26201:42)
    at config.transactAsync (<embedded>:26176:36)
    at Config.transactAsync (<embedded>:22754:28)
    at PackageManager.activatePackages (<embedded>:26174:23)
    at PackageManager.activate (<embedded>:26153:50)
    at loadStatePromise.loadState.then (<embedded>:1118:27)
    at <anonymous>:null:null
```

**Comment by ppo** [comment]
Atom 1.30.0, Tasks 2.10.1
Tried to re-install it but still not working.

```
Error: Grammar missing required scopeName property: ~/.atom/TasksGrammar.cson
    at GrammarRegistry.createGrammar (<embedded>:24828:21)
    at GrammarRegistry.readGrammarSync (<embedded>:24820:23)
    at GrammarRegistry.loadGrammarSync (<embedded>:24789:32)
    at Object.updateGrammar (~/macbook/tilde/.atom/packages/tasks/lib/tasks.coffee:198:34)
    at ~//macbook/tilde/.atom/packages/tasks/lib/tasks.coffee:85:24
    at Config.observeKeyPath (<embedded>:22944:11)
    at Config.observe (<embedded>:22373:25)
    at Object.activate (~/macbook/tilde/.atom/packages/tasks/lib/tasks.coffee:82:19)
    at Package.activateNow (<embedded>:75328:33)
    at measure (<embedded>:75304:33)
    at Package.measure (<embedded>:75186:25)
    at activationPromise.Promise (<embedded>:75298:20)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:75296:38)
    at PackageManager.activatePackage (<embedded>:26201:42)
    at config.transactAsync (<embedded>:26176:36)
    at Config.transactAsync (<embedded>:22754:28)
    at PackageManager.activatePackages (<embedded>:26174:23)
    at PackageManager.activate (<embedded>:26153:50)
    at loadStatePromise.loadState.then (<embedded>:1118:27)
    at <anonymous>:null:null
```

**Comment by ekoepplin** [comment]
@irrationalistic sry for that delay:

Grammar missing required scopeName property: /Users/user/.atom/TasksGrammar.cson
Hide Stack Trace
Error: Grammar missing required scopeName property: /Users/user/.atom/TasksGrammar.cson
    at GrammarRegistry.createGrammar (<embedded>:11:357847)
    at GrammarRegistry.readGrammarSync (<embedded>:11:357678)
    at GrammarRegistry.loadGrammarSync (<embedded>:11:357473)
    at Object.updateGrammar (/Users/user/.atom/packages/tasks/lib/tasks.coffee:198:34)
    at Object.activate (/Users/user/.atom/packages/tasks/lib/tasks.coffee:99:12)
    at Package.activateNow (<embedded>:11:2955986)
    at measure (<embedded>:11:2955398)
    at Package.measure (<embedded>:11:2953029)
    at activationPromise.activationPromise.Promise (<embedded>:11:2955258)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:2955201)
    at PackageManager.activatePackage (<embedded>:11:379950)
    at config.transactAsync (<embedded>:11:379566)
    at Config.transactAsync (<embedded>:11:329753)
    at PackageManager.activatePackages (<embedded>:11:379516)
    at PackageManager.activate (<embedded>:11:379134)
    at t.loadState.then (<embedded>:1:642865)
    at <anonymous>:null:null

**Comment by phil-r** [comment]
Just got the same error today after updating atom:

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.10.1


### Stack Trace

Failed to activate the tasks package

```
At Grammar missing required scopeName property: /Users/phil/.atom/TasksGrammar.cson

Error: Grammar missing required scopeName property: /Users/phil/.atom/TasksGrammar.cson
    at GrammarRegistry.createGrammar (<embedded>:11:358995)
    at GrammarRegistry.readGrammarSync (<embedded>:11:358826)
    at GrammarRegistry.loadGrammarSync (<embedded>:11:358621)
    at Object.updateGrammar (/packages/tasks/lib/tasks.coffee:198:34)
    at Object.activate (/packages/tasks/lib/tasks.coffee:99:12)
    at Package.activateNow (<embedded>:11:3418998)
    at measure (<embedded>:11:3418410)
    at Package.measure (<embedded>:11:3416041)
    at activationPromise.activationPromise.Promise (<embedded>:11:3418270)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3418213)
    at PackageManager.activatePackage (<embedded>:11:381112)
    at config.transactAsync (<embedded>:11:380728)
    at Config.transactAsync (<embedded>:11:330844)
    at PackageManager.activatePackages (<embedded>:11:380678)
    at PackageManager.activate (<embedded>:11:380296)
    at t.loadState.then (<embedded>:1:708815)
    at <anonymous>:null:null

```

### Commands

```
     -1:55.3.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-runner 2.7.1 
atom-ternjs 0.19.1 
busy-signal 2.0.1 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.4.0 
emmet 2.4.3 
intentions 1.1.5 
language-elixir 0.22.1 
language-jade 0.7.3 
language-lua 0.9.11 
language-matlab 0.2.1 
language-postcss 1.3.1 
language-pug 0.0.22 
language-rust 0.4.12 
language-vue 0.24.0 
linter 2.3.0 
linter-coffeelint 2.0.14 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-flake8 2.4.0 
linter-jsxhint 0.1.2 
linter-lua 2.0.0 
linter-rust 1.0.1 
linter-ui-default 1.7.1 
markdown-preview-plus 3.8.1 
minimap 4.29.9 
monokai 0.24.0 
prettier-atom 0.56.6 
react 0.18.0 
svg-preview 0.14.0 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
terminal-tab 0.5.7 
vim-mode-plus 1.36.0 
```
