### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by phreakmania** [irrationalistic/atom-tasks#95]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-tasks-master](https://github.com/irrationalistic/atom-tasks) package 2.10.1

### Stack Trace

Failed to load the atom-tasks-master package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-tasks-master/lib/tasks.coffee:2:5)
    at /packages/atom-tasks-master/lib/tasks.coffee:1:1)
    at /packages/atom-tasks-master/lib/tasks.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:818:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-jest-snippets 2.0.0 
atom-spotify2 2.1.2 
tasks 2.10.1 
atom-ternjs 0.18.3 
atom-transpose 0.3.5 
atom-underscore 0.1.3 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
autocomplete-modules 1.11.0 
busy-signal 1.4.3 
case-keep-replace 0.6.1 
change-case 0.6.5 
color-picker 2.2.5 
copy-path 0.5.1 
docblockr 0.13.6 
dracula-syntax 2.0.6 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
es6-javascript 1.0.0 
file-icons 2.1.16 
git-plus 7.10.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.0 
language-babel 2.84.0 
linter 2.0.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
local-history 4.3.1 
lodash-snippets 2.0.0 
pigments 0.40.2 
prettier-atom 0.51.0 
project-manager 3.3.5 
react-es7-snippets 0.3.13 
related 0.3.5 
set-syntax 0.4.0 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
tab-foldername-index 3.3.0 
toggle-quotes 1.1.0 
tree-view-copy-relative-path 1.2.0 
```

**Comment by phreakmania** [comment]
I forgot to mention, that module "underscore" is no longer available...

**Comment by irrationalistic** [comment]
That's strange! Can you try running `apm install` from command line? Or re-installing the tasks package? Underscore is still available on NPM, so it should be installable.

**Comment by irrationalistic** [comment]
Closing for now, but feel free to re-open if it persists!
