### ISSUE TITLE
Uncaught TypeError: ref3.tokenizedBuffer.onDidTokenize is not a function

### ISSUE THREAD

**Issue by kupkovski** [irrationalistic/atom-tasks#96]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [tasks](https://github.com/irrationalistic/atom-tasks) package 2.10.1

### Stack Trace

Uncaught TypeError: ref3.tokenizedBuffer.onDidTokenize is not a function

```
At /Users/andrekupkovski/.atom/packages/tasks/lib/views/task-status-view.coffee:25

TypeError: ref3.tokenizedBuffer.onDidTokenize is not a function
    at HTMLDivElement.TaskStatusView.subscribeToActiveTextEditor (/packages/tasks/lib/views/task-status-view.coffee:25:8)
    at /packages/tasks/lib/views/task-status-view.coffee:10:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:441:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:48)
    at Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:558:23)
    at Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:524:18)
    at HTMLElement.pane:show-previous-item (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:27:54)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -9:59.3.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -9:55.6.0 core:backspace (input.hidden-input)
  2x -9:48 core:close (input.hidden-input)
     -0:33.5.0 atomatigit:toggle (div.file-list-view.list-view)
     -0:21.4.0 editor:move-selection-left (input.hidden-input)
     -0:20.7.0 pane:show-previous-item (input.hidden-input)
     -0:15.1.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atomatigit 1.5.5 
goto-definition 1.3.4 
gruvbox 1.0.7 
language-diff 0.7.0 
tasks 2.10.1 
```

**Comment by irrationalistic** [comment]
Thanks for posting this! Could you add some more details on how to reproduce this issue? Is there a sample file you started with?
